
services:
  tensorflow:
    container_name: bird-identification
    build: .
    volumes:
      - ./app:/app/scripts
      - ./models:/app/models
      - ./input:/app/input
    command: tail -f /dev/null
    stdin_open: true
    tty: true
